# ============================================================
# FightVex — fill REAL_AGG for fighters MISSING stats (targeted merge).
#
# Reuses fetch_stats.py's ESPN aggregation but only fetches fighters not already
# in stats.generated.ts and MERGES them in — fast, and never touches the fighters
# already captured. Lower concurrency than the full fetch for reliability on the
# stragglers. Run after adding fighters, or to retry transient failures:
#   python scripts/fetch_stats_missing.py
# ============================================================
import re, json
from concurrent.futures import ThreadPoolExecutor
import fetch_stats as fs

def main():
    text = open(fs.OUT, encoding="utf-8").read()
    m = re.search(r"REAL_AGG: Record<string, RealAgg> = (\{.*\});", text, re.S)
    existing = json.loads(m.group(1)) if m else {}

    gen = open(fs.GEN, encoding="utf-8").read()
    try:
        gen += "\n" + open(fs.OVERRIDE, encoding="utf-8").read()
    except FileNotFoundError:
        pass
    pairs = re.findall(r'"id":\s*"(\d+)",\s*"slug":\s*"([^"]+)"', gen)
    ids = sorted({fid for fid, slug in pairs if not slug.startswith("ufc-")})
    missing = [i for i in ids if i not in existing]
    print(f"{len(existing)} existing, {len(missing)} missing - fetching the missing")

    out = dict(existing)
    got = 0
    with ThreadPoolExecutor(max_workers=6) as ex:  # gentle: reliable on stragglers
        for fid, agg in ex.map(fs.agg_fighter, missing):
            if agg:
                out[fid] = agg
                got += 1
    print(f"  filled {got}/{len(missing)} (now {len(out)} total)")

    banner = (
        "// ============================================================\n"
        "// AUTO-GENERATED by scripts/fetch_stats.py - DO NOT EDIT.\n"
        "// REAL aggregated fight statistics from the ESPN public MMA API\n"
        "// (recent fights). Keyed by ESPN athlete id. fighters.ts turns\n"
        "// these into the model's per-fighter metrics. Regenerate with:\n"
        "//   python scripts/fetch_stats.py\n"
        "// ============================================================\n"
        "/* eslint-disable */\n\n"
        "export interface RealAgg {\n"
        "  fights: number; minutes: number;\n"
        "  sigL: number; sigA: number; oSigL: number; oSigA: number;\n"
        "  tdL: number; tdA: number; oTdL: number; oTdA: number;\n"
        "  kd: number; oKd: number; sub: number; ctrl: number;\n"
        "}\n\n"
        f"export const REAL_AGG: Record<string, RealAgg> = {json.dumps(out, indent=2)};\n"
    )
    open(fs.OUT, "w", encoding="utf-8", newline="\n").write(banner)
    print(f"  wrote {fs.OUT}")

if __name__ == "__main__":
    main()
