// Generate per-fighter CURRENT recent-form features (from real recent fights) so
// production can feed the GBM the same features it was trained on. Written to
// src/lib/data/form.generated.ts, keyed by ESPN athlete id. Fighters not in the
// map fall back to neutral defaults at inference.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const { bouts } = JSON.parse(readFileSync(join(ROOT, "backtest", "history.json"), "utf8"));
const NOW = new Date("2026-06-06").getTime();

// Only emit form for fighters the app can actually simulate (the live roster) —
// the backtest uses history.json directly, so historical-only opponents don't
// need to ship in the client bundle. Keeps form.generated.ts small.
const ROSTER = new Set();
for (const file of ["src/lib/data/espn.generated.ts", "src/lib/data/rankings.override.ts"]) {
  const txt = readFileSync(join(ROOT, file), "utf8");
  for (const m of txt.matchAll(/"id":\s*"(\d+)"/g)) ROSTER.add(m[1]);
}
const fightMinutes = (b) => b.finished ? (b.endRound - 1) * 5 + 2.5 : b.maxRounds * 5;

const byF = new Map();
for (const b of bouts) for (const s of b.sides) { if (!byF.has(s.id)) byF.set(s.id, []); byF.get(s.id).push(b); }

const FORM = {};
for (const [id, list] of byF) {
  if (!ROSTER.has(id)) continue; // roster-only (production-predictable fighters)
  list.sort((a, b) => new Date(a.date) - new Date(b.date));
  const res = [];
  for (let i = list.length - 1; i >= 0; i--) { const b = list[i], me = b.sides.find((s) => s.id === id); if (!me) continue; res.push({ won: me.winner, lost: !me.winner && b.sides.some((s) => s.winner), finished: b.finished, mins: fightMinutes(b), t: new Date(b.date).getTime() }); }
  if (res.length < 2) continue; // need a couple of fights for meaningful form
  const decay = 0.8; let ws = 0, w = 0; res.forEach((r, i) => { const wt = decay ** i; ws += wt * (r.won ? 1 : 0); w += wt; });
  const recForm = w ? ws / w : 0.5;
  let streak = 0; for (const r of res) { if (streak >= 0 && r.won) streak++; else if (streak <= 0 && r.lost) streak--; else break; }
  const activity = res.filter((r) => (NOW - r.t) < 730 * 864e5).length;
  let fs = 0, fw = 0; res.forEach((r, i) => { if (r.won) { const wt = decay ** i; fs += wt * (r.finished ? 1 : 0); fw += wt; } });
  const recFinish = fw ? fs / fw : 0.5;
  const recent = res.slice(0, 5), avgDur = recent.reduce((s, r) => s + r.mins, 0) / recent.length;
  FORM[id] = { recForm: +recForm.toFixed(3), streak, activity, recFinish: +recFinish.toFixed(3), avgDur: +avgDur.toFixed(1) };
}
writeFileSync(join(ROOT, "src", "lib", "data", "form.generated.ts"),
`// AUTO-GENERATED by scripts/gen-form.mjs — per-fighter recent-form features from
// real recent fights (ESPN), keyed by athlete id. Feeds the GBM ensemble.
/* eslint-disable */
export interface FormFeat { recForm: number; streak: number; activity: number; recFinish: number; avgDur: number; }
export const FORM_DEFAULT: FormFeat = { recForm: 0.5, streak: 0, activity: 1, recFinish: 0.5, avgDur: 12.5 };
export const FORM: Record<string, FormFeat> = ${JSON.stringify(FORM)};
export function formFor(id: string): FormFeat { return FORM[id] || FORM_DEFAULT; }
`);
console.log(`wrote form for ${Object.keys(FORM).length} fighters → src/lib/data/form.generated.ts`);
