import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/Badge";
import { Panel } from "@/components/ui/Panel";

const DOCS: Record<string, { title: string; intro: string; sections: { h: string; p: string }[] }> = {
  terms: {
    title: "Terms of Service",
    intro: "These plain-language terms summarize how FightVex may be used. This is demonstration copy, not legal advice; a production launch requires review by a qualified attorney.",
    sections: [
      { h: "1. Informational use only", p: "FightVex provides analytics, statistics and probabilistic simulations for information and entertainment. Nothing on the platform is betting, investment or financial advice, and we do not accept or place wagers." },
      { h: "2. No guarantee of outcomes", p: "All predictions are probabilistic. We make no representation that any prediction, value signal or simulation will be accurate or profitable. You are solely responsible for any decisions you make." },
      { h: "3. Eligibility & age", p: "You must be of legal age in your jurisdiction (21+ in many regions) and located where accessing this content is lawful. We may use geofencing and verification to enforce this." },
      { h: "4. Acceptable use", p: "You may not scrape, resell, or redistribute our data, attempt to reverse-engineer the models, or use the service to violate any law or third-party terms." },
      { h: "5. Data sources", p: "Data is obtained from licensed providers, official sources, public records and clearly attributed news. We are not affiliated with any MMA promotion or sportsbook." },
      { h: "6. Limitation of liability", p: "The service is provided 'as is.' To the maximum extent permitted by law, FightVex is not liable for losses arising from use of the platform." },
    ],
  },
  privacy: {
    title: "Privacy Policy",
    intro: "How we handle data. Demonstration copy — a production policy must be GDPR/CCPA-reviewed by counsel.",
    sections: [
      { h: "1. What we collect", p: "Account details (email), usage analytics, and preferences such as watchlists and saved fighters. We aim to minimize collection." },
      { h: "2. How we use it", p: "To operate the service, personalize alerts, process subscriptions, and improve our models in aggregate. We do not sell personal data." },
      { h: "3. Cookies & analytics", p: "We use privacy-respecting analytics and essential cookies. You can control non-essential cookies." },
      { h: "4. Your rights", p: "Depending on your region you may access, correct, export or delete your data. Contact us to exercise these rights." },
      { h: "5. Security", p: "Encryption in transit and at rest, least-privilege access, and audit logging. No method is perfectly secure, but we follow industry best practices." },
    ],
  },
  "affiliate-disclosure": {
    title: "Affiliate Disclosure",
    intro: "Transparency about how we may earn revenue.",
    sections: [
      { h: "1. Affiliate relationships", p: "Where shown, links to licensed sportsbooks may be affiliate links. If you sign up or act through them, we may receive a commission at no extra cost to you." },
      { h: "2. Editorial independence", p: "Affiliate relationships never influence Vex AI outputs, value signals, or analysis. Predictions are generated by Vex AI, not by commercial partnerships." },
      { h: "3. Region awareness", p: "Affiliate links are shown only where lawful and are tailored to your jurisdiction. They are clearly labeled." },
      { h: "4. No guarantees", p: "We do not endorse betting and do not guarantee any outcome. Please gamble responsibly. 21+." },
    ],
  },
};

export function generateStaticParams() {
  return Object.keys(DOCS).map((doc) => ({ doc }));
}

export async function generateMetadata({ params }: { params: Promise<{ doc: string }> }): Promise<Metadata> {
  const { doc } = await params;
  const d = DOCS[doc];
  return { title: d?.title ?? "Legal", description: d?.intro?.slice(0, 155), alternates: { canonical: `/legal/${doc}` } };
}

export default async function LegalPage({ params }: { params: Promise<{ doc: string }> }) {
  const { doc } = await params;
  const data = DOCS[doc];
  if (!data) notFound();

  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <Badge variant="steel">Legal</Badge>
      <h1 className="mt-3 font-display text-4xl font-bold uppercase sm:text-5xl">{data.title}</h1>
      <p className="mt-3 text-sm text-muted">{data.intro}</p>
      {data.sections.map((s) => (
        <Panel key={s.h} className="reveal mt-5 p-6">
          <h2 className="mb-2 font-display text-lg font-bold uppercase">{s.h}</h2>
          <p className="text-sm leading-relaxed text-muted">{s.p}</p>
        </Panel>
      ))}
      <p className="reveal mt-8 text-[11px] text-muted">Last updated: 2026 · Demonstration document.</p>
    </div>
  );
}
