// ============================================================
// AUTO-GENERATED by scripts/backtest.mjs — DO NOT EDIT BY HAND.
// Leakage-free historical backtest of the Vex AI engine: every bout's
// inputs were rebuilt from ONLY each fighter's prior fights, then run
// through the live engine and compared to the real ESPN result.
// Regenerate: node scripts/fetch-history.mjs && node scripts/backtest.mjs 1000
// ============================================================
/* eslint-disable */
export interface BacktestCalibration { bucket: string; predicted: number; actual: number; n: number; }
export interface BacktestRecord {
  generatedAt: string;
  fighters: number;          // distinct fighters in the dataset
  boutsCollected: number;    // real bouts with full reconstructable history
  backtested: number;        // bouts actually scored (both sides ≥2 prior fights)
  yearFrom: number; yearTo: number;
  accuracy: number;          // pick accuracy, full set
  accuracyRecent: number;    // pick accuracy, held-out recent 30%
  logLoss: number; logLossRecent: number; brier: number;
  realFinishRate: number;    // real finish (non-decision) rate in the set
  calibration: BacktestCalibration[];
}
export const BACKTEST: BacktestRecord = {
  generatedAt: "2026-06-08T17:50:43.038Z",
  fighters: 13866,
  boutsCollected: 20108,
  backtested: 10206,
  yearFrom: 1993,
  yearTo: 2026,
  accuracy: 0.646,
  accuracyRecent: 0.635,
  logLoss: 0.625,
  logLossRecent: 0.627,
  brier: 0.218,
  realFinishRate: 0.549,
  calibration: [{"bucket":"0.1-0.2","predicted":0.177,"actual":0.109,"n":101},{"bucket":"0.2-0.3","predicted":0.257,"actual":0.153,"n":616},{"bucket":"0.3-0.4","predicted":0.353,"actual":0.31,"n":1811},{"bucket":"0.4-0.5","predicted":0.451,"actual":0.455,"n":2202},{"bucket":"0.5-0.6","predicted":0.549,"actual":0.545,"n":2607},{"bucket":"0.6-0.7","predicted":0.646,"actual":0.689,"n":1816},{"bucket":"0.7-0.8","predicted":0.74,"actual":0.805,"n":945},{"bucket":"0.8-0.9","predicted":0.829,"actual":0.916,"n":107}],
};
