// AUTO-GENERATED by scripts/gen-calibration.mjs — Platt calibration fit on the
// LIVE graded prediction record, sample-size shrunk toward identity. Identity
// (a=1,b=0) = no effect (small record). Monotonic — never changes the favored side.
/* eslint-disable */
export interface LiveCalibration { a: number; b: number; n: number; updatedAt: string; }
export const LIVE_CALIBRATION: LiveCalibration = {"a":1,"b":0,"n":5,"updatedAt":"2026-06-07T21:33:28.532Z"};
