// ============================================================
// AUTO-GENERATED by scripts/fetch-espn.mjs — DO NOT EDIT BY HAND.
// Real data from the ESPN public MMA API (keyless, read-only).
// Regenerate with: npm run fetch:espn
// Generated: 2026-06-08T22:42:05.461Z
// ============================================================
/* eslint-disable */

export interface RawFighter {
  id: string; slug: string; name: string; nickname?: string;
  country: string; flag: string; age: number; heightCm: number;
  reachCm: number; stance: string; weightClass: string;
  champion?: boolean; title?: string; ranking?: number;
  record: { wins: number; losses: number; draws: number; ko: number; sub: number; dec: number };
}
export interface RawBout {
  id: string; fighterA: string; fighterB: string;
  weightClass: string; rounds: 3 | 5; boutOrder: number;
}
export interface RawEvent {
  id: string; slug: string; name: string; org: string; date: string;
  venue: string; city: string; country: string; broadcast: string;
  status: "upcoming" | "live" | "completed"; bouts: RawBout[];
}

export const GENERATED_AT = "2026-06-08T22:42:05.463Z";

export const REAL_FIGHTERS: RawFighter[] = [
  {
    "id": "3023804",
    "slug": "steve-garcia",
    "name": "Steve Garcia",
    "nickname": "Mean Machine",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 34,
    "heightCm": 183,
    "reachCm": 191,
    "stance": "Southpaw",
    "weightClass": "Featherweight",
    "record": {
      "wins": 19,
      "losses": 5,
      "draws": 0,
      "ko": 15,
      "sub": 0,
      "dec": 4
    }
  },
  {
    "id": "4881999",
    "slug": "diego-lopes",
    "name": "Diego Lopes",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 31,
    "heightCm": 180,
    "reachCm": 184,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "record": {
      "wins": 27,
      "losses": 8,
      "draws": 0,
      "ko": 11,
      "sub": 12,
      "dec": 4
    }
  },
  {
    "id": "4329444",
    "slug": "kyle-daukaus",
    "name": "Kyle Daukaus",
    "nickname": "The D'Arce Knight",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 33,
    "heightCm": 188,
    "reachCm": 193,
    "stance": "Southpaw",
    "weightClass": "Middleweight",
    "record": {
      "wins": 17,
      "losses": 4,
      "draws": 0,
      "ko": 2,
      "sub": 12,
      "dec": 3
    }
  },
  {
    "id": "5061870",
    "slug": "bo-nickal",
    "name": "Bo Nickal",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 30,
    "heightCm": 185,
    "reachCm": 193,
    "stance": "Southpaw",
    "weightClass": "Middleweight",
    "record": {
      "wins": 8,
      "losses": 1,
      "draws": 0,
      "ko": 3,
      "sub": 4,
      "dec": 1
    }
  },
  {
    "id": "2504988",
    "slug": "michael-chandler",
    "name": "Michael Chandler",
    "nickname": "Iron",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 40,
    "heightCm": 173,
    "reachCm": 182,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "ranking": 4,
    "record": {
      "wins": 23,
      "losses": 10,
      "draws": 0,
      "ko": 11,
      "sub": 7,
      "dec": 5
    }
  },
  {
    "id": "5122238",
    "slug": "mauricio-ruffy",
    "name": "Mauricio Ruffy",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 29,
    "heightCm": 180,
    "reachCm": 191,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "record": {
      "wins": 13,
      "losses": 2,
      "draws": 0,
      "ko": 12,
      "sub": 0,
      "dec": 1
    }
  },
  {
    "id": "2560713",
    "slug": "derrick-lewis",
    "name": "Derrick Lewis",
    "nickname": "The Black Beast",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 41,
    "heightCm": 191,
    "reachCm": 201,
    "stance": "Orthodox",
    "weightClass": "Heavyweight",
    "ranking": 3,
    "record": {
      "wins": 29,
      "losses": 13,
      "draws": 0,
      "ko": 24,
      "sub": 1,
      "dec": 4
    }
  },
  {
    "id": "4049391",
    "slug": "josh-hokit",
    "name": "Josh Hokit",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 28,
    "heightCm": 185,
    "reachCm": 187,
    "stance": "Orthodox",
    "weightClass": "Heavyweight",
    "record": {
      "wins": 9,
      "losses": 0,
      "draws": 0,
      "ko": 5,
      "sub": 3,
      "dec": 1
    }
  },
  {
    "id": "4079149",
    "slug": "aiemann-zahabi",
    "name": "Aiemann Zahabi",
    "country": "Canada",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/can.png",
    "age": 38,
    "heightCm": 173,
    "reachCm": 174,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "record": {
      "wins": 14,
      "losses": 2,
      "draws": 0,
      "ko": 6,
      "sub": 2,
      "dec": 6
    }
  },
  {
    "id": "4205093",
    "slug": "sean-omalley",
    "name": "Sean O'Malley",
    "nickname": "Suga",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 31,
    "heightCm": 180,
    "reachCm": 183,
    "stance": "Switch",
    "weightClass": "Bantamweight",
    "record": {
      "wins": 19,
      "losses": 3,
      "draws": 0,
      "ko": 12,
      "sub": 1,
      "dec": 6
    }
  },
  {
    "id": "4426000",
    "slug": "ciryl-gane",
    "name": "Ciryl Gane",
    "nickname": "Bon Gamin",
    "country": "France",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/fra.png",
    "age": 36,
    "heightCm": 193,
    "reachCm": 206,
    "stance": "Orthodox",
    "weightClass": "Heavyweight",
    "ranking": 4,
    "record": {
      "wins": 13,
      "losses": 2,
      "draws": 0,
      "ko": 6,
      "sub": 3,
      "dec": 4
    }
  },
  {
    "id": "4705658",
    "slug": "alex-pereira",
    "name": "Alex Pereira",
    "nickname": "Poatan",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 38,
    "heightCm": 193,
    "reachCm": 201,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "record": {
      "wins": 13,
      "losses": 3,
      "draws": 0,
      "ko": 11,
      "sub": 0,
      "dec": 2
    }
  },
  {
    "id": "3022345",
    "slug": "justin-gaethje",
    "name": "Justin Gaethje",
    "nickname": "The Highlight",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 37,
    "heightCm": 180,
    "reachCm": 178,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "ranking": 3,
    "record": {
      "wins": 27,
      "losses": 5,
      "draws": 0,
      "ko": 20,
      "sub": 1,
      "dec": 6
    }
  },
  {
    "id": "4350812",
    "slug": "ilia-topuria",
    "name": "Ilia Topuria",
    "nickname": "El Matador",
    "country": "Georgia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/geo.png",
    "age": 29,
    "heightCm": 170,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "record": {
      "wins": 17,
      "losses": 0,
      "draws": 0,
      "ko": 7,
      "sub": 8,
      "dec": 2
    }
  },
  {
    "id": "4292349",
    "slug": "karol-rosa",
    "name": "Karol Rosa",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 31,
    "heightCm": 165,
    "reachCm": 171,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "record": {
      "wins": 19,
      "losses": 7,
      "draws": 0,
      "ko": 4,
      "sub": 2,
      "dec": 13
    }
  },
  {
    "id": "5110469",
    "slug": "luana-santos",
    "name": "Luana Santos",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 26,
    "heightCm": 168,
    "reachCm": 170,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "record": {
      "wins": 10,
      "losses": 2,
      "draws": 0,
      "ko": 1,
      "sub": 5,
      "dec": 4
    }
  },
  {
    "id": "4393818",
    "slug": "gaston-bolanos",
    "name": "Gaston Bolaños",
    "nickname": "The Dreamkiller",
    "country": "Peru",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/per.png",
    "age": 33,
    "heightCm": 170,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "record": {
      "wins": 8,
      "losses": 5,
      "draws": 0,
      "ko": 6,
      "sub": 0,
      "dec": 2
    }
  },
  {
    "id": "5212738",
    "slug": "michael-aswell",
    "name": "Michael Aswell",
    "nickname": "The Texas Kid",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 25,
    "heightCm": 173,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "record": {
      "wins": 11,
      "losses": 4,
      "draws": 0,
      "ko": 6,
      "sub": 0,
      "dec": 5
    }
  },
  {
    "id": "3020408",
    "slug": "allan-nascimento",
    "name": "Allan Nascimento",
    "nickname": "Puro Osso",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 34,
    "heightCm": 173,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "record": {
      "wins": 22,
      "losses": 6,
      "draws": 0,
      "ko": 1,
      "sub": 16,
      "dec": 5
    }
  },
  {
    "id": "4815978",
    "slug": "mitch-raposo",
    "name": "Mitch Raposo",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 27,
    "heightCm": 165,
    "reachCm": 164,
    "stance": "Switch",
    "weightClass": "Flyweight",
    "record": {
      "wins": 10,
      "losses": 3,
      "draws": 0,
      "ko": 4,
      "sub": 3,
      "dec": 3
    }
  },
  {
    "id": "5127984",
    "slug": "melissa-mullins",
    "name": "Melissa Mullins",
    "nickname": "No Mess",
    "country": "England",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
    "age": 34,
    "heightCm": 170,
    "reachCm": 173,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "record": {
      "wins": 7,
      "losses": 2,
      "draws": 0,
      "ko": 4,
      "sub": 0,
      "dec": 3
    }
  },
  {
    "id": "5310274",
    "slug": "bia-mesquita",
    "name": "Bia Mesquita",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 35,
    "heightCm": 163,
    "reachCm": 171,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "record": {
      "wins": 7,
      "losses": 0,
      "draws": 0,
      "ko": 1,
      "sub": 5,
      "dec": 1
    }
  },
  {
    "id": "4686734",
    "slug": "melsik-baghdasaryan",
    "name": "Melsik Baghdasaryan",
    "nickname": "The Gun",
    "country": "Armenia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/arm.png",
    "age": 34,
    "heightCm": 175,
    "reachCm": 178,
    "stance": "Southpaw",
    "weightClass": "Featherweight",
    "record": {
      "wins": 8,
      "losses": 3,
      "draws": 0,
      "ko": 5,
      "sub": 0,
      "dec": 3
    }
  },
  {
    "id": "5308768",
    "slug": "murtazali-magomedov",
    "name": "Murtazali Magomedov",
    "nickname": "The Highlight",
    "country": "Kyrgyzstan",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/kgz.png",
    "age": 26,
    "heightCm": 180,
    "reachCm": 179,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "record": {
      "wins": 10,
      "losses": 0,
      "draws": 0,
      "ko": 5,
      "sub": 5,
      "dec": 0
    }
  },
  {
    "id": "5144066",
    "slug": "kevin-borjas",
    "name": "Kevin Borjas",
    "nickname": "El Gallo Negro",
    "country": "Peru",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/per.png",
    "age": 28,
    "heightCm": 165,
    "reachCm": 173,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "record": {
      "wins": 10,
      "losses": 5,
      "draws": 0,
      "ko": 8,
      "sub": 0,
      "dec": 2
    }
  },
  {
    "id": "5157669",
    "slug": "andre-lima",
    "name": "Andre Lima",
    "nickname": "Mascote",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 27,
    "heightCm": 170,
    "reachCm": 170,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "record": {
      "wins": 11,
      "losses": 0,
      "draws": 0,
      "ko": 5,
      "sub": 1,
      "dec": 5
    }
  },
  {
    "id": "4875511",
    "slug": "christian-rodriguez",
    "name": "Christian Rodriguez",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 28,
    "heightCm": 170,
    "reachCm": 182,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "record": {
      "wins": 12,
      "losses": 4,
      "draws": 0,
      "ko": 3,
      "sub": 4,
      "dec": 5
    }
  },
  {
    "id": "5027356",
    "slug": "hyder-amil",
    "name": "Hyder Amil",
    "nickname": "The Hurricane",
    "country": "Philippines",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/phi.png",
    "age": 36,
    "heightCm": 175,
    "reachCm": 178,
    "stance": "Switch",
    "weightClass": "Featherweight",
    "record": {
      "wins": 11,
      "losses": 2,
      "draws": 0,
      "ko": 6,
      "sub": 1,
      "dec": 4
    }
  },
  {
    "id": "3957071",
    "slug": "giga-chikadze",
    "name": "Giga Chikadze",
    "nickname": "Ninja",
    "country": "Georgia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/geo.png",
    "age": 37,
    "heightCm": 183,
    "reachCm": 188,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "record": {
      "wins": 15,
      "losses": 6,
      "draws": 0,
      "ko": 9,
      "sub": 1,
      "dec": 5
    }
  },
  {
    "id": "4884877",
    "slug": "vinicius-oliveira",
    "name": "Vinicius Oliveira",
    "nickname": "LokDog",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 30,
    "heightCm": 175,
    "reachCm": 179,
    "stance": "Switch",
    "weightClass": "Bantamweight",
    "record": {
      "wins": 23,
      "losses": 4,
      "draws": 0,
      "ko": 16,
      "sub": 2,
      "dec": 5
    }
  },
  {
    "id": "3994033",
    "slug": "ion-cutelaba",
    "name": "Ion Cutelaba",
    "nickname": "The Hulk",
    "country": "Moldova",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/mda.png",
    "age": 32,
    "heightCm": 185,
    "reachCm": 191,
    "stance": "Southpaw",
    "weightClass": "Light Heavyweight",
    "record": {
      "wins": 20,
      "losses": 11,
      "draws": 1,
      "ko": 13,
      "sub": 4,
      "dec": 3
    }
  },
  {
    "id": "5216713",
    "slug": "navajo-stirling",
    "name": "Navajo Stirling",
    "country": "New Zealand",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/nzl.png",
    "age": 28,
    "heightCm": 193,
    "reachCm": 201,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "record": {
      "wins": 9,
      "losses": 0,
      "draws": 0,
      "ko": 5,
      "sub": 0,
      "dec": 4
    }
  },
  {
    "id": "2613374",
    "slug": "kyoji-horiguchi",
    "name": "Kyoji Horiguchi",
    "nickname": "Karate Kid",
    "country": "Japan",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/jpn.png",
    "age": 35,
    "heightCm": 163,
    "reachCm": 160,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "record": {
      "wins": 36,
      "losses": 5,
      "draws": 0,
      "ko": 15,
      "sub": 6,
      "dec": 15
    }
  },
  {
    "id": "4236504",
    "slug": "manel-kape",
    "name": "Manel Kape",
    "nickname": "Starboy",
    "country": "Portugal",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/por.png",
    "age": 32,
    "heightCm": 165,
    "reachCm": 173,
    "stance": "Southpaw",
    "weightClass": "Flyweight",
    "record": {
      "wins": 22,
      "losses": 7,
      "draws": 0,
      "ko": 14,
      "sub": 5,
      "dec": 3
    }
  },
  {
    "id": "5149439",
    "slug": "jean-matsumoto",
    "name": "Jean Matsumoto",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 26,
    "heightCm": 168,
    "reachCm": 174,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "record": {
      "wins": 17,
      "losses": 2,
      "draws": 0,
      "ko": 3,
      "sub": 6,
      "dec": 8
    }
  },
  {
    "id": "5196459",
    "slug": "bekzat-almakhan",
    "name": "Bekzat Almakhan",
    "nickname": "The Turan Warrior",
    "country": "Kazakhstan",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/kaz.png",
    "age": 28,
    "heightCm": 170,
    "reachCm": 173,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "record": {
      "wins": 12,
      "losses": 3,
      "draws": 0,
      "ko": 10,
      "sub": 1,
      "dec": 1
    }
  },
  {
    "id": "4738749",
    "slug": "andreas-gustafsson",
    "name": "Andreas Gustafsson",
    "nickname": "Bane",
    "country": "Sweden",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/swe.png",
    "age": 35,
    "heightCm": 185,
    "reachCm": 187,
    "stance": "Orthodox",
    "weightClass": "Welterweight",
    "record": {
      "wins": 12,
      "losses": 3,
      "draws": 0,
      "ko": 8,
      "sub": 2,
      "dec": 2
    }
  },
  {
    "id": "5289841",
    "slug": "daniil-donchenko",
    "name": "Daniil Donchenko",
    "country": "Ukraine",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/ukr.png",
    "age": 24,
    "heightCm": 180,
    "reachCm": 180,
    "stance": "Orthodox",
    "weightClass": "Welterweight",
    "record": {
      "wins": 14,
      "losses": 2,
      "draws": 0,
      "ko": 9,
      "sub": 2,
      "dec": 3
    }
  },
  {
    "id": "4687104",
    "slug": "javier-reyes",
    "name": "Javier Reyes",
    "nickname": "Blair",
    "country": "Colombia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/col.png",
    "age": 32,
    "heightCm": 178,
    "reachCm": 185,
    "stance": "--",
    "weightClass": "Featherweight",
    "record": {
      "wins": 23,
      "losses": 5,
      "draws": 0,
      "ko": 11,
      "sub": 8,
      "dec": 4
    }
  },
  {
    "id": "5204223",
    "slug": "kaan-ofli",
    "name": "Kaan Ofli",
    "nickname": "Genghis",
    "country": "Australia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/aus.png",
    "age": 32,
    "heightCm": 170,
    "reachCm": 168,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "record": {
      "wins": 14,
      "losses": 4,
      "draws": 1,
      "ko": 2,
      "sub": 7,
      "dec": 5
    }
  },
  {
    "id": "4422103",
    "slug": "nursulton-ruziboev",
    "name": "Nursulton Ruziboev",
    "nickname": "Black",
    "country": "Uzbekistan",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/uzb.png",
    "age": 32,
    "heightCm": 196,
    "reachCm": 193,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "record": {
      "wins": 36,
      "losses": 9,
      "draws": 2,
      "ko": 13,
      "sub": 20,
      "dec": 3
    }
  },
  {
    "id": "5211225",
    "slug": "andrey-pulyaev",
    "name": "Andrey Pulyaev",
    "country": "Russia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
    "age": 28,
    "heightCm": 193,
    "reachCm": 198,
    "stance": "Southpaw",
    "weightClass": "Middleweight",
    "record": {
      "wins": 10,
      "losses": 4,
      "draws": 0,
      "ko": 6,
      "sub": 2,
      "dec": 2
    }
  },
  {
    "id": "5264398",
    "slug": "julius-walker",
    "name": "Julius Walker",
    "nickname": "Juice Box",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 26,
    "heightCm": 193,
    "reachCm": 198,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "record": {
      "wins": 7,
      "losses": 2,
      "draws": 0,
      "ko": 4,
      "sub": 2,
      "dec": 1
    }
  },
  {
    "id": "5291025",
    "slug": "abdul-rakhman-yakhyaev",
    "name": "Abdul-Rakhman Yakhyaev",
    "nickname": "Hunter",
    "country": "Türkiye",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/tur.png",
    "age": 25,
    "heightCm": 188,
    "reachCm": 198,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "record": {
      "wins": 9,
      "losses": 0,
      "draws": 0,
      "ko": 3,
      "sub": 5,
      "dec": 1
    }
  },
  {
    "id": "5290958",
    "slug": "eric-nolan",
    "name": "Eric Nolan",
    "nickname": "Nightime",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 28,
    "heightCm": 188,
    "reachCm": 188,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "record": {
      "wins": 8,
      "losses": 4,
      "draws": 0,
      "ko": 4,
      "sub": 2,
      "dec": 2
    }
  },
  {
    "id": "5350562",
    "slug": "farman-hasanov",
    "name": "Farman Hasanov",
    "country": "Azerbaijan",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/aze.png",
    "age": 30,
    "heightCm": 183,
    "reachCm": 189,
    "stance": "--",
    "weightClass": "Welterweight",
    "record": {
      "wins": 5,
      "losses": 0,
      "draws": 0,
      "ko": 4,
      "sub": 0,
      "dec": 1
    }
  },
  {
    "id": "3077822",
    "slug": "abus-magomedov",
    "name": "Abus Magomedov",
    "country": "Germany",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/ger.png",
    "age": 35,
    "heightCm": 188,
    "reachCm": 198,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "record": {
      "wins": 28,
      "losses": 7,
      "draws": 1,
      "ko": 14,
      "sub": 7,
      "dec": 7
    }
  },
  {
    "id": "4012999",
    "slug": "michal-oleksiejczuk",
    "name": "Michal Oleksiejczuk",
    "nickname": "Hussar",
    "country": "Poland",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/pol.png",
    "age": 31,
    "heightCm": 183,
    "reachCm": 188,
    "stance": "Southpaw",
    "weightClass": "Middleweight",
    "record": {
      "wins": 22,
      "losses": 9,
      "draws": 0,
      "ko": 16,
      "sub": 1,
      "dec": 5
    }
  },
  {
    "id": "4684776",
    "slug": "ikram-aliskerov",
    "name": "Ikram Aliskerov",
    "country": "Russia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
    "age": 33,
    "heightCm": 183,
    "reachCm": 193,
    "stance": "Southpaw",
    "weightClass": "Middleweight",
    "record": {
      "wins": 17,
      "losses": 2,
      "draws": 0,
      "ko": 7,
      "sub": 5,
      "dec": 5
    }
  },
  {
    "id": "5077131",
    "slug": "brunno-ferreira",
    "name": "Brunno Ferreira",
    "nickname": "The Hulk",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 33,
    "heightCm": 178,
    "reachCm": 183,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "record": {
      "wins": 15,
      "losses": 3,
      "draws": 0,
      "ko": 9,
      "sub": 5,
      "dec": 1
    }
  },
  {
    "id": "4294926",
    "slug": "asu-almabayev",
    "name": "Asu Almabayev",
    "nickname": "Zulfikar",
    "country": "Kazakhstan",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/kaz.png",
    "age": 32,
    "heightCm": 163,
    "reachCm": 165,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "record": {
      "wins": 23,
      "losses": 3,
      "draws": 0,
      "ko": 3,
      "sub": 10,
      "dec": 10
    }
  },
  {
    "id": "4375156",
    "slug": "charles-johnson",
    "name": "Charles Johnson",
    "nickname": "InnerG",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 35,
    "heightCm": 175,
    "reachCm": 178,
    "stance": "Switch",
    "weightClass": "Flyweight",
    "record": {
      "wins": 19,
      "losses": 8,
      "draws": 0,
      "ko": 8,
      "sub": 3,
      "dec": 8
    }
  },
  {
    "id": "5074130",
    "slug": "nazim-sadykhov",
    "name": "Nazim Sadykhov",
    "nickname": "Black Wolf",
    "country": "Azerbaijan",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/aze.png",
    "age": 32,
    "heightCm": 178,
    "reachCm": 175,
    "stance": "Southpaw",
    "weightClass": "Lightweight",
    "record": {
      "wins": 11,
      "losses": 2,
      "draws": 1,
      "ko": 8,
      "sub": 2,
      "dec": 1
    }
  },
  {
    "id": "5170144",
    "slug": "matheus-camilo",
    "name": "Matheus Camilo",
    "nickname": "Jaguar",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 25,
    "heightCm": 178,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "record": {
      "wins": 10,
      "losses": 3,
      "draws": 0,
      "ko": 4,
      "sub": 2,
      "dec": 4
    }
  },
  {
    "id": "4418962",
    "slug": "michel-pereira",
    "name": "Michel Pereira",
    "nickname": "Demolidor",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 32,
    "heightCm": 185,
    "reachCm": 185,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "record": {
      "wins": 32,
      "losses": 14,
      "draws": 0,
      "ko": 11,
      "sub": 9,
      "dec": 12
    }
  },
  {
    "id": "4421784",
    "slug": "shara-magomedov",
    "name": "Shara Magomedov",
    "nickname": "Bullet",
    "country": "Russia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
    "age": 32,
    "heightCm": 188,
    "reachCm": 185,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "record": {
      "wins": 16,
      "losses": 1,
      "draws": 0,
      "ko": 12,
      "sub": 0,
      "dec": 4
    }
  },
  {
    "id": "4339488",
    "slug": "rafael-fiziev",
    "name": "Rafael Fiziev",
    "nickname": "Ataman",
    "country": "Azerbaijan",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/aze.png",
    "age": 33,
    "heightCm": 173,
    "reachCm": 180,
    "stance": "Switch",
    "weightClass": "Lightweight",
    "record": {
      "wins": 13,
      "losses": 5,
      "draws": 0,
      "ko": 8,
      "sub": 1,
      "dec": 4
    }
  },
  {
    "id": "4896616",
    "slug": "manuel-torres",
    "name": "Manuel Torres",
    "nickname": "El Loco",
    "country": "Mexico",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/mex.png",
    "age": 31,
    "heightCm": 178,
    "reachCm": 185,
    "stance": "Switch",
    "weightClass": "Lightweight",
    "record": {
      "wins": 17,
      "losses": 3,
      "draws": 0,
      "ko": 9,
      "sub": 7,
      "dec": 1
    }
  },
  {
    "id": "5143223",
    "slug": "zachary-reese",
    "name": "Zachary Reese",
    "nickname": "Savage",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 32,
    "heightCm": 193,
    "reachCm": 196,
    "stance": "Switch",
    "weightClass": "Middleweight",
    "record": {
      "wins": 10,
      "losses": 3,
      "draws": 0,
      "ko": 5,
      "sub": 3,
      "dec": 2
    }
  },
  {
    "id": "5291085",
    "slug": "ryan-gandra",
    "name": "Ryan Gandra",
    "nickname": "Problema",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 31,
    "heightCm": 185,
    "reachCm": 189,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "record": {
      "wins": 9,
      "losses": 1,
      "draws": 0,
      "ko": 6,
      "sub": 1,
      "dec": 2
    }
  },
  {
    "id": "4215200",
    "slug": "wang-cong",
    "name": "Wang Cong",
    "nickname": "The Joker",
    "country": "China",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
    "age": 34,
    "heightCm": 168,
    "reachCm": 166,
    "stance": "Southpaw",
    "weightClass": "Women's Flyweight",
    "record": {
      "wins": 9,
      "losses": 1,
      "draws": 0,
      "ko": 2,
      "sub": 2,
      "dec": 5
    }
  },
  {
    "id": "4243624",
    "slug": "tracy-cortez",
    "name": "Tracy Cortez",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 32,
    "heightCm": 165,
    "reachCm": 166,
    "stance": "Orthodox",
    "weightClass": "Women's Flyweight",
    "record": {
      "wins": 12,
      "losses": 3,
      "draws": 0,
      "ko": 1,
      "sub": 1,
      "dec": 10
    }
  },
  {
    "id": "4424224",
    "slug": "ode-osbourne",
    "name": "Ode' Osbourne",
    "nickname": "The Jamaican Sensation",
    "country": "Jamaica",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/jam.png",
    "age": 34,
    "heightCm": 170,
    "reachCm": 185,
    "stance": "Southpaw",
    "weightClass": "Flyweight",
    "record": {
      "wins": 13,
      "losses": 10,
      "draws": 0,
      "ko": 6,
      "sub": 4,
      "dec": 3
    }
  },
  {
    "id": "4686725",
    "slug": "cody-durden",
    "name": "Cody Durden",
    "nickname": "Custom Made",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 35,
    "heightCm": 170,
    "reachCm": 170,
    "stance": "Southpaw",
    "weightClass": "Flyweight",
    "record": {
      "wins": 18,
      "losses": 10,
      "draws": 1,
      "ko": 6,
      "sub": 6,
      "dec": 6
    }
  },
  {
    "id": "3163637",
    "slug": "cody-garbrandt",
    "name": "Cody Garbrandt",
    "nickname": "No Love",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 34,
    "heightCm": 173,
    "reachCm": 166,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "ranking": 4,
    "record": {
      "wins": 15,
      "losses": 7,
      "draws": 0,
      "ko": 11,
      "sub": 0,
      "dec": 4
    }
  },
  {
    "id": "3998248",
    "slug": "adrian-yanez",
    "name": "Adrian Yanez",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 32,
    "heightCm": 170,
    "reachCm": 178,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "record": {
      "wins": 17,
      "losses": 6,
      "draws": 1,
      "ko": 11,
      "sub": 2,
      "dec": 4
    }
  },
  {
    "id": "5144068",
    "slug": "cesar-almeida",
    "name": "Cesar Almeida",
    "nickname": "Cesinha",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 38,
    "heightCm": 185,
    "reachCm": 188,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "record": {
      "wins": 7,
      "losses": 2,
      "draws": 0,
      "ko": 5,
      "sub": 0,
      "dec": 2
    }
  },
  {
    "id": "5292022",
    "slug": "damian-pinas",
    "name": "Damian Pinas",
    "nickname": "The Baba Yaga",
    "country": "Aruba",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/aru.png",
    "age": 24,
    "heightCm": 185,
    "reachCm": 202,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "record": {
      "wins": 9,
      "losses": 1,
      "draws": 0,
      "ko": 8,
      "sub": 1,
      "dec": 0
    }
  },
  {
    "id": "4688447",
    "slug": "kai-kamaka-iii",
    "name": "Kai Kamaka III",
    "nickname": "The Fighting Hawaiian",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 31,
    "heightCm": 170,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "record": {
      "wins": 18,
      "losses": 7,
      "draws": 1,
      "ko": 3,
      "sub": 1,
      "dec": 14
    }
  },
  {
    "id": "5146696",
    "slug": "luke-riley",
    "name": "Luke Riley",
    "country": "England",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
    "age": 26,
    "heightCm": 175,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "record": {
      "wins": 13,
      "losses": 0,
      "draws": 0,
      "ko": 9,
      "sub": 0,
      "dec": 4
    }
  },
  {
    "id": "3009717",
    "slug": "robert-whittaker",
    "name": "Robert Whittaker",
    "nickname": "The Reaper",
    "country": "Australia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/aus.png",
    "age": 35,
    "heightCm": 183,
    "reachCm": 187,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "ranking": 2,
    "record": {
      "wins": 27,
      "losses": 9,
      "draws": 0,
      "ko": 11,
      "sub": 5,
      "dec": 11
    }
  },
  {
    "id": "3026263",
    "slug": "nikita-krylov",
    "name": "Nikita Krylov",
    "nickname": "The Miner",
    "country": "Russia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
    "age": 34,
    "heightCm": 191,
    "reachCm": 197,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "record": {
      "wins": 31,
      "losses": 11,
      "draws": 0,
      "ko": 13,
      "sub": 16,
      "dec": 2
    }
  },
  {
    "id": "5214652",
    "slug": "gable-steveson",
    "name": "Gable Steveson",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 26,
    "heightCm": 185,
    "reachCm": 0,
    "stance": "--",
    "weightClass": "Heavyweight",
    "record": {
      "wins": 3,
      "losses": 0,
      "draws": 0,
      "ko": 3,
      "sub": 0,
      "dec": 0
    }
  },
  {
    "id": "5293987",
    "slug": "elisha-ellison",
    "name": "Elisha Ellison",
    "nickname": "Snack Panther",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 29,
    "heightCm": 183,
    "reachCm": 198,
    "stance": "Orthodox",
    "weightClass": "Heavyweight",
    "record": {
      "wins": 5,
      "losses": 2,
      "draws": 0,
      "ko": 4,
      "sub": 1,
      "dec": 0
    }
  },
  {
    "id": "4239928",
    "slug": "brandon-royval",
    "name": "Brandon Royval",
    "nickname": "Raw Dawg",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 33,
    "heightCm": 175,
    "reachCm": 173,
    "stance": "Southpaw",
    "weightClass": "Flyweight",
    "ranking": 9,
    "record": {
      "wins": 17,
      "losses": 9,
      "draws": 0,
      "ko": 4,
      "sub": 9,
      "dec": 4
    }
  },
  {
    "id": "5147737",
    "slug": "loneer-kavanagh",
    "name": "Lone'er Kavanagh",
    "country": "England",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
    "age": 26,
    "heightCm": 168,
    "reachCm": 170,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "record": {
      "wins": 10,
      "losses": 1,
      "draws": 0,
      "ko": 4,
      "sub": 1,
      "dec": 5
    }
  },
  {
    "id": "4294504",
    "slug": "cory-sandhagen",
    "name": "Cory Sandhagen",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 34,
    "heightCm": 180,
    "reachCm": 178,
    "stance": "Switch",
    "weightClass": "Bantamweight",
    "ranking": 3,
    "record": {
      "wins": 18,
      "losses": 6,
      "draws": 0,
      "ko": 8,
      "sub": 3,
      "dec": 7
    }
  },
  {
    "id": "4410868",
    "slug": "mario-bautista",
    "name": "Mario Bautista",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 32,
    "heightCm": 175,
    "reachCm": 175,
    "stance": "Switch",
    "weightClass": "Bantamweight",
    "record": {
      "wins": 17,
      "losses": 3,
      "draws": 0,
      "ko": 3,
      "sub": 7,
      "dec": 7
    }
  },
  {
    "id": "4008549",
    "slug": "paddy-pimblett",
    "name": "Paddy Pimblett",
    "nickname": "The Baddy",
    "country": "England",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
    "age": 31,
    "heightCm": 178,
    "reachCm": 185,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "record": {
      "wins": 23,
      "losses": 4,
      "draws": 0,
      "ko": 7,
      "sub": 10,
      "dec": 6
    }
  },
  {
    "id": "4895362",
    "slug": "benoit-saint-denis",
    "name": "Benoît Saint Denis",
    "nickname": "God of War",
    "country": "France",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/fra.png",
    "age": 30,
    "heightCm": 180,
    "reachCm": 185,
    "stance": "Southpaw",
    "weightClass": "Lightweight",
    "record": {
      "wins": 17,
      "losses": 3,
      "draws": 0,
      "ko": 6,
      "sub": 11,
      "dec": 0
    }
  },
  {
    "id": "2614933",
    "slug": "max-holloway",
    "name": "Max Holloway",
    "nickname": "Blessed",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 34,
    "heightCm": 180,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "ranking": 2,
    "record": {
      "wins": 27,
      "losses": 9,
      "draws": 0,
      "ko": 12,
      "sub": 2,
      "dec": 13
    }
  },
  {
    "id": "3022677",
    "slug": "conor-mcgregor",
    "name": "Conor McGregor",
    "nickname": "The Notorious",
    "country": "Ireland",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/irl.png",
    "age": 37,
    "heightCm": 175,
    "reachCm": 188,
    "stance": "Southpaw",
    "weightClass": "Welterweight",
    "record": {
      "wins": 22,
      "losses": 6,
      "draws": 0,
      "ko": 19,
      "sub": 1,
      "dec": 2
    }
  },
  {
    "id": "2506250",
    "slug": "jan-blachowicz",
    "name": "Jan Blachowicz",
    "country": "Poland",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/pol.png",
    "age": 43,
    "heightCm": 188,
    "reachCm": 198,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "champion": true,
    "title": "UFC Light Heavyweight Champion",
    "ranking": 0,
    "record": {
      "wins": 29,
      "losses": 11,
      "draws": 2,
      "ko": 9,
      "sub": 9,
      "dec": 11
    }
  },
  {
    "id": "4285679",
    "slug": "israel-adesanya",
    "name": "Israel Adesanya",
    "nickname": "The Last Stylebender",
    "country": "Nigeria",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/ngr.png",
    "age": 36,
    "heightCm": 193,
    "reachCm": 203,
    "stance": "Switch",
    "weightClass": "Middleweight",
    "champion": true,
    "title": "UFC Middleweight Champion",
    "ranking": 0,
    "record": {
      "wins": 24,
      "losses": 6,
      "draws": 0,
      "ko": 16,
      "sub": 0,
      "dec": 8
    }
  },
  {
    "id": "3088812",
    "slug": "kamaru-usman",
    "name": "Kamaru Usman",
    "nickname": "Nigerian Nightmare",
    "country": "Nigeria",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/ngr.png",
    "age": 39,
    "heightCm": 183,
    "reachCm": 193,
    "stance": "Switch",
    "weightClass": "Welterweight",
    "champion": true,
    "title": "UFC Welterweight Champion",
    "ranking": 0,
    "record": {
      "wins": 21,
      "losses": 4,
      "draws": 0,
      "ko": 9,
      "sub": 1,
      "dec": 11
    }
  },
  {
    "id": "2504169",
    "slug": "charles-oliveira",
    "name": "Charles Oliveira",
    "nickname": "Do Bronxs",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 36,
    "heightCm": 178,
    "reachCm": 188,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "champion": true,
    "title": "UFC Lightweight Champion",
    "ranking": 0,
    "record": {
      "wins": 37,
      "losses": 11,
      "draws": 0,
      "ko": 10,
      "sub": 22,
      "dec": 5
    }
  },
  {
    "id": "3949584",
    "slug": "alexander-volkanovski",
    "name": "Alexander Volkanovski",
    "nickname": "The Great",
    "country": "Australia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/aus.png",
    "age": 37,
    "heightCm": 168,
    "reachCm": 182,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "champion": true,
    "title": "UFC Featherweight Champion",
    "ranking": 0,
    "record": {
      "wins": 28,
      "losses": 4,
      "draws": 0,
      "ko": 13,
      "sub": 3,
      "dec": 12
    }
  },
  {
    "id": "3031559",
    "slug": "aljamain-sterling",
    "name": "Aljamain Sterling",
    "nickname": "Funk Master",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 36,
    "heightCm": 170,
    "reachCm": 180,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "champion": true,
    "title": "UFC Bantamweight Champion",
    "ranking": 0,
    "record": {
      "wins": 26,
      "losses": 5,
      "draws": 0,
      "ko": 3,
      "sub": 8,
      "dec": 15
    }
  },
  {
    "id": "4189320",
    "slug": "deiveson-figueiredo",
    "name": "Deiveson Figueiredo",
    "nickname": "Deus da Guerra",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 38,
    "heightCm": 165,
    "reachCm": 173,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "champion": true,
    "title": "UFC Flyweight Champion",
    "ranking": 0,
    "record": {
      "wins": 25,
      "losses": 7,
      "draws": 1,
      "ko": 9,
      "sub": 9,
      "dec": 7
    }
  },
  {
    "id": "3032973",
    "slug": "rose-namajunas",
    "name": "Rose Namajunas",
    "nickname": "Thug",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 33,
    "heightCm": 165,
    "reachCm": 165,
    "stance": "Orthodox",
    "weightClass": "Women's Flyweight",
    "champion": true,
    "title": "UFC Women's Strawweight Champion",
    "ranking": 0,
    "record": {
      "wins": 15,
      "losses": 8,
      "draws": 0,
      "ko": 2,
      "sub": 6,
      "dec": 7
    }
  },
  {
    "id": "2504951",
    "slug": "stipe-miocic",
    "name": "Stipe Miocic",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 43,
    "heightCm": 193,
    "reachCm": 203,
    "stance": "Orthodox",
    "weightClass": "Heavyweight",
    "ranking": 2,
    "record": {
      "wins": 20,
      "losses": 5,
      "draws": 0,
      "ko": 14,
      "sub": 1,
      "dec": 5
    }
  },
  {
    "id": "3922557",
    "slug": "curtis-blaydes",
    "name": "Curtis Blaydes",
    "nickname": "Razor",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 35,
    "heightCm": 193,
    "reachCm": 203,
    "stance": "Orthodox",
    "weightClass": "Heavyweight",
    "ranking": 5,
    "record": {
      "wins": 19,
      "losses": 6,
      "draws": 0,
      "ko": 13,
      "sub": 0,
      "dec": 6
    }
  },
  {
    "id": "2993650",
    "slug": "alexander-volkov",
    "name": "Alexander Volkov",
    "nickname": "Drago",
    "country": "Russia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
    "age": 37,
    "heightCm": 201,
    "reachCm": 203,
    "stance": "Orthodox",
    "weightClass": "Heavyweight",
    "ranking": 6,
    "record": {
      "wins": 40,
      "losses": 11,
      "draws": 0,
      "ko": 24,
      "sub": 4,
      "dec": 12
    }
  },
  {
    "id": "4410084",
    "slug": "jairzinho-rozenstruik",
    "name": "Jairzinho Rozenstruik",
    "nickname": "Bigi Boy",
    "country": "Suriname",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/sur.png",
    "age": 38,
    "heightCm": 188,
    "reachCm": 198,
    "stance": "Orthodox",
    "weightClass": "Heavyweight",
    "ranking": 7,
    "record": {
      "wins": 15,
      "losses": 6,
      "draws": 0,
      "ko": 13,
      "sub": 0,
      "dec": 2
    }
  },
  {
    "id": "2335516",
    "slug": "alistair-overeem",
    "name": "Alistair Overeem",
    "nickname": "The Demolition Man",
    "country": "Netherlands",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/ned.png",
    "age": 46,
    "heightCm": 193,
    "reachCm": 203,
    "stance": "Orthodox",
    "weightClass": "Heavyweight",
    "ranking": 8,
    "record": {
      "wins": 47,
      "losses": 19,
      "draws": 0,
      "ko": 25,
      "sub": 17,
      "dec": 5
    }
  },
  {
    "id": "2335530",
    "slug": "ryan-bader",
    "name": "Ryan Bader",
    "nickname": "Darth",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 43,
    "heightCm": 188,
    "reachCm": 185,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "ranking": 9,
    "record": {
      "wins": 31,
      "losses": 8,
      "draws": 0,
      "ko": 13,
      "sub": 3,
      "dec": 15
    }
  },
  {
    "id": "2504929",
    "slug": "glover-teixeira",
    "name": "Glover Teixeira",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 46,
    "heightCm": 188,
    "reachCm": 193,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "ranking": 3,
    "record": {
      "wins": 33,
      "losses": 9,
      "draws": 0,
      "ko": 18,
      "sub": 10,
      "dec": 5
    }
  },
  {
    "id": "3156612",
    "slug": "jiri-prochazka",
    "name": "Jiří Procházka",
    "country": "Czechia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/cze.png",
    "age": 33,
    "heightCm": 191,
    "reachCm": 203,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "ranking": 4,
    "record": {
      "wins": 32,
      "losses": 6,
      "draws": 1,
      "ko": 28,
      "sub": 3,
      "dec": 1
    }
  },
  {
    "id": "4079314",
    "slug": "aleksandar-rakic",
    "name": "Aleksandar Rakic",
    "nickname": "Rocket",
    "country": "Serbia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/ser.png",
    "age": 34,
    "heightCm": 193,
    "reachCm": 198,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "ranking": 5,
    "record": {
      "wins": 14,
      "losses": 6,
      "draws": 0,
      "ko": 9,
      "sub": 1,
      "dec": 4
    }
  },
  {
    "id": "3955014",
    "slug": "vadim-nemkov",
    "name": "Vadim Nemkov",
    "country": "Russia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
    "age": 33,
    "heightCm": 183,
    "reachCm": 193,
    "stance": "--",
    "weightClass": "Heavyweight",
    "ranking": 6,
    "record": {
      "wins": 20,
      "losses": 2,
      "draws": 0,
      "ko": 10,
      "sub": 6,
      "dec": 4
    }
  },
  {
    "id": "4233039",
    "slug": "dominick-reyes",
    "name": "Dominick Reyes",
    "nickname": "The Devastator",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 36,
    "heightCm": 193,
    "reachCm": 196,
    "stance": "Southpaw",
    "weightClass": "Light Heavyweight",
    "ranking": 7,
    "record": {
      "wins": 16,
      "losses": 5,
      "draws": 0,
      "ko": 10,
      "sub": 2,
      "dec": 4
    }
  },
  {
    "id": "3112020",
    "slug": "corey-anderson",
    "name": "Corey Anderson",
    "nickname": "Overtime",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 36,
    "heightCm": 191,
    "reachCm": 201,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "ranking": 8,
    "record": {
      "wins": 21,
      "losses": 6,
      "draws": 0,
      "ko": 9,
      "sub": 0,
      "dec": 12
    }
  },
  {
    "id": "3045798",
    "slug": "thiago-santos",
    "name": "Thiago Santos",
    "nickname": "Marreta",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 42,
    "heightCm": 188,
    "reachCm": 198,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "ranking": 10,
    "record": {
      "wins": 22,
      "losses": 13,
      "draws": 0,
      "ko": 15,
      "sub": 1,
      "dec": 6
    }
  },
  {
    "id": "4080826",
    "slug": "paulo-costa",
    "name": "Paulo Costa",
    "nickname": "The Eraser",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 35,
    "heightCm": 185,
    "reachCm": 183,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "ranking": 3,
    "record": {
      "wins": 16,
      "losses": 4,
      "draws": 0,
      "ko": 12,
      "sub": 1,
      "dec": 3
    }
  },
  {
    "id": "3154860",
    "slug": "jared-cannonier",
    "name": "Jared Cannonier",
    "nickname": "The Killa Gorilla",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 42,
    "heightCm": 180,
    "reachCm": 197,
    "stance": "Switch",
    "weightClass": "Middleweight",
    "ranking": 5,
    "record": {
      "wins": 18,
      "losses": 9,
      "draws": 0,
      "ko": 11,
      "sub": 2,
      "dec": 5
    }
  },
  {
    "id": "4001851",
    "slug": "marvin-vettori",
    "name": "Marvin Vettori",
    "nickname": "The Italian Dream",
    "country": "Italy",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/ita.png",
    "age": 32,
    "heightCm": 183,
    "reachCm": 188,
    "stance": "Southpaw",
    "weightClass": "Middleweight",
    "ranking": 6,
    "record": {
      "wins": 19,
      "losses": 10,
      "draws": 1,
      "ko": 2,
      "sub": 9,
      "dec": 8
    }
  },
  {
    "id": "2560056",
    "slug": "derek-brunson",
    "name": "Derek Brunson",
    "nickname": "Blonde",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 42,
    "heightCm": 185,
    "reachCm": 196,
    "stance": "Southpaw",
    "weightClass": "Middleweight",
    "ranking": 7,
    "record": {
      "wins": 24,
      "losses": 9,
      "draws": 0,
      "ko": 12,
      "sub": 4,
      "dec": 8
    }
  },
  {
    "id": "3897436",
    "slug": "darren-till",
    "name": "Darren Till",
    "nickname": "The Gorilla",
    "country": "England",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
    "age": 33,
    "heightCm": 183,
    "reachCm": 189,
    "stance": "Southpaw",
    "weightClass": "Middleweight",
    "ranking": 8,
    "record": {
      "wins": 18,
      "losses": 5,
      "draws": 1,
      "ko": 10,
      "sub": 2,
      "dec": 6
    }
  },
  {
    "id": "3074102",
    "slug": "jack-hermansson",
    "name": "Jack Hermansson",
    "nickname": "The Joker",
    "country": "Norway",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/nor.png",
    "age": 37,
    "heightCm": 185,
    "reachCm": 197,
    "stance": "Orthodox",
    "weightClass": "Welterweight",
    "ranking": 9,
    "record": {
      "wins": 24,
      "losses": 10,
      "draws": 0,
      "ko": 11,
      "sub": 6,
      "dec": 7
    }
  },
  {
    "id": "2431313",
    "slug": "gegard-mousasi",
    "name": "Gegard Mousasi",
    "nickname": "The Dreamcatcher",
    "country": "Netherlands",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/ned.png",
    "age": 40,
    "heightCm": 188,
    "reachCm": 193,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "ranking": 10,
    "record": {
      "wins": 49,
      "losses": 9,
      "draws": 2,
      "ko": 28,
      "sub": 11,
      "dec": 10
    }
  },
  {
    "id": "3088810",
    "slug": "colby-covington",
    "name": "Colby Covington",
    "nickname": "Chaos",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 38,
    "heightCm": 180,
    "reachCm": 183,
    "stance": "Orthodox",
    "weightClass": "Welterweight",
    "ranking": 2,
    "record": {
      "wins": 17,
      "losses": 5,
      "draws": 0,
      "ko": 3,
      "sub": 5,
      "dec": 9
    }
  },
  {
    "id": "2500691",
    "slug": "douglas-lima",
    "name": "Douglas Lima",
    "nickname": "The Phenom",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 38,
    "heightCm": 185,
    "reachCm": 189,
    "stance": "--",
    "weightClass": "Middleweight",
    "ranking": 3,
    "record": {
      "wins": 33,
      "losses": 12,
      "draws": 0,
      "ko": 14,
      "sub": 11,
      "dec": 8
    }
  },
  {
    "id": "3152929",
    "slug": "leon-edwards",
    "name": "Leon Edwards",
    "nickname": "Rocky",
    "country": "England",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
    "age": 34,
    "heightCm": 188,
    "reachCm": 188,
    "stance": "Southpaw",
    "weightClass": "Welterweight",
    "ranking": 4,
    "record": {
      "wins": 22,
      "losses": 6,
      "draws": 0,
      "ko": 7,
      "sub": 3,
      "dec": 12
    }
  },
  {
    "id": "3090197",
    "slug": "gilbert-burns",
    "name": "Gilbert Burns",
    "nickname": "Durinho",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 39,
    "heightCm": 178,
    "reachCm": 180,
    "stance": "Orthodox",
    "weightClass": "Welterweight",
    "ranking": 5,
    "record": {
      "wins": 22,
      "losses": 10,
      "draws": 0,
      "ko": 6,
      "sub": 9,
      "dec": 7
    }
  },
  {
    "id": "2615077",
    "slug": "stephen-thompson",
    "name": "Stephen Thompson",
    "nickname": "Wonderboy",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 43,
    "heightCm": 183,
    "reachCm": 191,
    "stance": "Orthodox",
    "weightClass": "Welterweight",
    "ranking": 6,
    "record": {
      "wins": 17,
      "losses": 9,
      "draws": 1,
      "ko": 8,
      "sub": 1,
      "dec": 8
    }
  },
  {
    "id": "2960681",
    "slug": "michael-chiesa",
    "name": "Michael Chiesa",
    "nickname": "Maverick",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 38,
    "heightCm": 185,
    "reachCm": 192,
    "stance": "Southpaw",
    "weightClass": "Welterweight",
    "ranking": 7,
    "record": {
      "wins": 20,
      "losses": 7,
      "draws": 0,
      "ko": 0,
      "sub": 13,
      "dec": 7
    }
  },
  {
    "id": "3045887",
    "slug": "vicente-luque",
    "name": "Vicente Luque",
    "nickname": "The Silent Assassin",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 34,
    "heightCm": 180,
    "reachCm": 192,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "ranking": 8,
    "record": {
      "wins": 24,
      "losses": 12,
      "draws": 1,
      "ko": 11,
      "sub": 10,
      "dec": 3
    }
  },
  {
    "id": "2500857",
    "slug": "jorge-masvidal",
    "name": "Jorge Masvidal",
    "nickname": "Gamebred",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 41,
    "heightCm": 180,
    "reachCm": 188,
    "stance": "Orthodox",
    "weightClass": "Welterweight",
    "ranking": 9,
    "record": {
      "wins": 35,
      "losses": 17,
      "draws": 0,
      "ko": 16,
      "sub": 2,
      "dec": 17
    }
  },
  {
    "id": "2501814",
    "slug": "rory-macdonald",
    "name": "Rory MacDonald",
    "nickname": "The Red King",
    "country": "Canada",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/can.png",
    "age": 36,
    "heightCm": 183,
    "reachCm": 193,
    "stance": "Orthodox",
    "weightClass": "Welterweight",
    "ranking": 10,
    "record": {
      "wins": 23,
      "losses": 10,
      "draws": 1,
      "ko": 7,
      "sub": 9,
      "dec": 7
    }
  },
  {
    "id": "2506549",
    "slug": "dustin-poirier",
    "name": "Dustin Poirier",
    "nickname": "The Diamond",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 37,
    "heightCm": 175,
    "reachCm": 183,
    "stance": "Southpaw",
    "weightClass": "Lightweight",
    "ranking": 2,
    "record": {
      "wins": 30,
      "losses": 10,
      "draws": 0,
      "ko": 16,
      "sub": 7,
      "dec": 7
    }
  },
  {
    "id": "3085551",
    "slug": "beneil-dariush",
    "name": "Beneil Dariush",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 37,
    "heightCm": 178,
    "reachCm": 183,
    "stance": "Southpaw",
    "weightClass": "Lightweight",
    "ranking": 5,
    "record": {
      "wins": 23,
      "losses": 8,
      "draws": 1,
      "ko": 5,
      "sub": 8,
      "dec": 10
    }
  },
  {
    "id": "3109135",
    "slug": "dan-hooker",
    "name": "Dan Hooker",
    "nickname": "The Hangman",
    "country": "New Zealand",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/nzl.png",
    "age": 36,
    "heightCm": 183,
    "reachCm": 191,
    "stance": "Switch",
    "weightClass": "Lightweight",
    "ranking": 6,
    "record": {
      "wins": 24,
      "losses": 14,
      "draws": 0,
      "ko": 11,
      "sub": 7,
      "dec": 6
    }
  },
  {
    "id": "2335687",
    "slug": "rafael-dos-anjos",
    "name": "Rafael Dos Anjos",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 41,
    "heightCm": 173,
    "reachCm": 178,
    "stance": "Southpaw",
    "weightClass": "Welterweight",
    "ranking": 7,
    "record": {
      "wins": 32,
      "losses": 17,
      "draws": 0,
      "ko": 5,
      "sub": 11,
      "dec": 16
    }
  },
  {
    "id": "3332412",
    "slug": "islam-makhachev",
    "name": "Islam Makhachev",
    "country": "Russia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
    "age": 34,
    "heightCm": 178,
    "reachCm": 179,
    "stance": "Southpaw",
    "weightClass": "Welterweight",
    "ranking": 8,
    "record": {
      "wins": 28,
      "losses": 1,
      "draws": 0,
      "ko": 5,
      "sub": 13,
      "dec": 10
    }
  },
  {
    "id": "3099985",
    "slug": "paul-felder",
    "name": "Paul Felder",
    "nickname": "The Irish Dragon",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 42,
    "heightCm": 180,
    "reachCm": 178,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "ranking": 9,
    "record": {
      "wins": 17,
      "losses": 6,
      "draws": 0,
      "ko": 10,
      "sub": 1,
      "dec": 6
    }
  },
  {
    "id": "4021934",
    "slug": "gregor-gillespie",
    "name": "Gregor Gillespie",
    "nickname": "The Gift",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 39,
    "heightCm": 170,
    "reachCm": 180,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "ranking": 10,
    "record": {
      "wins": 14,
      "losses": 1,
      "draws": 0,
      "ko": 7,
      "sub": 5,
      "dec": 2
    }
  },
  {
    "id": "2532870",
    "slug": "patricio-pitbull",
    "name": "Patricio Pitbull",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 38,
    "heightCm": 168,
    "reachCm": 170,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "ranking": 3,
    "record": {
      "wins": 37,
      "losses": 9,
      "draws": 0,
      "ko": 13,
      "sub": 11,
      "dec": 13
    }
  },
  {
    "id": "3045737",
    "slug": "brian-ortega",
    "name": "Brian Ortega",
    "nickname": "T-City",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 35,
    "heightCm": 173,
    "reachCm": 175,
    "stance": "Switch",
    "weightClass": "Featherweight",
    "ranking": 4,
    "record": {
      "wins": 16,
      "losses": 5,
      "draws": 0,
      "ko": 3,
      "sub": 8,
      "dec": 5
    }
  },
  {
    "id": "3164030",
    "slug": "calvin-kattar",
    "name": "Calvin Kattar",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 38,
    "heightCm": 180,
    "reachCm": 183,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "ranking": 6,
    "record": {
      "wins": 23,
      "losses": 10,
      "draws": 0,
      "ko": 11,
      "sub": 2,
      "dec": 10
    }
  },
  {
    "id": "3155420",
    "slug": "yair-rodriguez",
    "name": "Yair Rodriguez",
    "nickname": "El Pantera",
    "country": "Mexico",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/mex.png",
    "age": 33,
    "heightCm": 180,
    "reachCm": 180,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "ranking": 7,
    "record": {
      "wins": 21,
      "losses": 5,
      "draws": 0,
      "ko": 9,
      "sub": 5,
      "dec": 7
    }
  },
  {
    "id": "2501685",
    "slug": "chan-sung-jung",
    "name": "Chan Sung Jung",
    "nickname": "The Korean Zombie",
    "country": "Korea",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/kor.png",
    "age": 39,
    "heightCm": 170,
    "reachCm": 183,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "ranking": 8,
    "record": {
      "wins": 17,
      "losses": 8,
      "draws": 0,
      "ko": 6,
      "sub": 8,
      "dec": 3
    }
  },
  {
    "id": "4011299",
    "slug": "josh-emmett",
    "name": "Josh Emmett",
    "nickname": "CC0",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 41,
    "heightCm": 168,
    "reachCm": 178,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "ranking": 9,
    "record": {
      "wins": 19,
      "losses": 7,
      "draws": 0,
      "ko": 7,
      "sub": 2,
      "dec": 10
    }
  },
  {
    "id": "2526299",
    "slug": "edson-barboza",
    "name": "Edson Barboza",
    "nickname": "Junior",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 40,
    "heightCm": 180,
    "reachCm": 191,
    "stance": "Orthodox",
    "weightClass": "Lightweight",
    "ranking": 10,
    "record": {
      "wins": 24,
      "losses": 14,
      "draws": 0,
      "ko": 14,
      "sub": 1,
      "dec": 9
    }
  },
  {
    "id": "4293517",
    "slug": "petr-yan",
    "name": "Petr Yan",
    "nickname": "No Mercy",
    "country": "Russia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
    "age": 33,
    "heightCm": 170,
    "reachCm": 170,
    "stance": "Switch",
    "weightClass": "Bantamweight",
    "ranking": 2,
    "record": {
      "wins": 20,
      "losses": 5,
      "draws": 0,
      "ko": 7,
      "sub": 1,
      "dec": 12
    }
  },
  {
    "id": "3090451",
    "slug": "rob-font",
    "name": "Rob Font",
    "country": "Puerto Rico",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/pur.png",
    "age": 38,
    "heightCm": 173,
    "reachCm": 182,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "ranking": 5,
    "record": {
      "wins": 22,
      "losses": 10,
      "draws": 0,
      "ko": 9,
      "sub": 4,
      "dec": 9
    }
  },
  {
    "id": "2447641",
    "slug": "jose-aldo",
    "name": "José Aldo",
    "nickname": "Junior",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 39,
    "heightCm": 170,
    "reachCm": 178,
    "stance": "Orthodox",
    "weightClass": "Featherweight",
    "ranking": 6,
    "record": {
      "wins": 32,
      "losses": 10,
      "draws": 0,
      "ko": 17,
      "sub": 1,
      "dec": 14
    }
  },
  {
    "id": "2335694",
    "slug": "frankie-edgar",
    "name": "Frankie Edgar",
    "nickname": "The Answer",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 44,
    "heightCm": 168,
    "reachCm": 173,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "ranking": 7,
    "record": {
      "wins": 23,
      "losses": 11,
      "draws": 1,
      "ko": 6,
      "sub": 4,
      "dec": 13
    }
  },
  {
    "id": "3045734",
    "slug": "pedro-munhoz",
    "name": "Pedro Munhoz",
    "nickname": "The Young Punisher",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 39,
    "heightCm": 168,
    "reachCm": 165,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "ranking": 8,
    "record": {
      "wins": 20,
      "losses": 10,
      "draws": 0,
      "ko": 5,
      "sub": 8,
      "dec": 7
    }
  },
  {
    "id": "2553310",
    "slug": "marlon-moraes",
    "name": "Marlon Moraes",
    "nickname": "Magic",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 38,
    "heightCm": 168,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "ranking": 9,
    "record": {
      "wins": 23,
      "losses": 13,
      "draws": 1,
      "ko": 10,
      "sub": 6,
      "dec": 7
    }
  },
  {
    "id": "2354364",
    "slug": "raphael-assuncao",
    "name": "Raphael Assuncao",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 43,
    "heightCm": 165,
    "reachCm": 169,
    "stance": "Orthodox",
    "weightClass": "Bantamweight",
    "ranking": 10,
    "record": {
      "wins": 28,
      "losses": 10,
      "draws": 0,
      "ko": 4,
      "sub": 10,
      "dec": 14
    }
  },
  {
    "id": "3027545",
    "slug": "brandon-moreno",
    "name": "Brandon Moreno",
    "nickname": "The Assassin Baby",
    "country": "Mexico",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/mex.png",
    "age": 32,
    "heightCm": 170,
    "reachCm": 178,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "ranking": 2,
    "record": {
      "wins": 23,
      "losses": 10,
      "draws": 2,
      "ko": 5,
      "sub": 11,
      "dec": 7
    }
  },
  {
    "id": "3081236",
    "slug": "adriano-moraes",
    "name": "Adriano Moraes",
    "nickname": "Mikinho",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 39,
    "heightCm": 173,
    "reachCm": 175,
    "stance": "--",
    "weightClass": "Flyweight",
    "ranking": 2,
    "record": {
      "wins": 22,
      "losses": 6,
      "draws": 0,
      "ko": 4,
      "sub": 12,
      "dec": 6
    }
  },
  {
    "id": "2512089",
    "slug": "demetrious-johnson",
    "name": "Demetrious Johnson",
    "nickname": "Mighty Mouse",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 39,
    "heightCm": 160,
    "reachCm": 168,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "ranking": 4,
    "record": {
      "wins": 25,
      "losses": 4,
      "draws": 1,
      "ko": 5,
      "sub": 8,
      "dec": 12
    }
  },
  {
    "id": "4064692",
    "slug": "askar-askarov",
    "name": "Askar Askarov",
    "nickname": "Bullet",
    "country": "Russia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
    "age": 33,
    "heightCm": 168,
    "reachCm": 170,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "ranking": 5,
    "record": {
      "wins": 15,
      "losses": 1,
      "draws": 1,
      "ko": 4,
      "sub": 7,
      "dec": 4
    }
  },
  {
    "id": "3155425",
    "slug": "alex-perez",
    "name": "Alex Perez",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 34,
    "heightCm": 168,
    "reachCm": 166,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "ranking": 6,
    "record": {
      "wins": 26,
      "losses": 10,
      "draws": 0,
      "ko": 7,
      "sub": 7,
      "dec": 12
    }
  },
  {
    "id": "2560746",
    "slug": "alexandre-pantoja",
    "name": "Alexandre Pantoja",
    "nickname": "The Cannibal",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 36,
    "heightCm": 165,
    "reachCm": 171,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "ranking": 7,
    "record": {
      "wins": 30,
      "losses": 6,
      "draws": 0,
      "ko": 8,
      "sub": 12,
      "dec": 10
    }
  },
  {
    "id": "4243885",
    "slug": "kai-kara-france",
    "name": "Kai Kara-France",
    "nickname": "Don't Blink",
    "country": "New Zealand",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/nzl.png",
    "age": 33,
    "heightCm": 163,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "ranking": 8,
    "record": {
      "wins": 25,
      "losses": 12,
      "draws": 0,
      "ko": 12,
      "sub": 3,
      "dec": 10
    }
  },
  {
    "id": "4280789",
    "slug": "rogerio-bontorin",
    "name": "Rogerio Bontorin",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 34,
    "heightCm": 165,
    "reachCm": 170,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "ranking": 10,
    "record": {
      "wins": 17,
      "losses": 5,
      "draws": 0,
      "ko": 3,
      "sub": 11,
      "dec": 3
    }
  },
  {
    "id": "2552777",
    "slug": "germaine-de-randamie",
    "name": "Germaine de Randamie",
    "nickname": "The Iron Lady",
    "country": "Netherlands",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/ned.png",
    "age": 42,
    "heightCm": 175,
    "reachCm": 180,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "ranking": 2,
    "record": {
      "wins": 10,
      "losses": 5,
      "draws": 0,
      "ko": 4,
      "sub": 1,
      "dec": 5
    }
  },
  {
    "id": "2951361",
    "slug": "julianna-pena",
    "name": "Julianna Peña",
    "nickname": "The Venezuelan Vixen",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 36,
    "heightCm": 168,
    "reachCm": 175,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "ranking": 3,
    "record": {
      "wins": 13,
      "losses": 6,
      "draws": 0,
      "ko": 3,
      "sub": 6,
      "dec": 4
    }
  },
  {
    "id": "3028404",
    "slug": "holly-holm",
    "name": "Holly Holm",
    "nickname": "The Preacher's Daughter",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 44,
    "heightCm": 173,
    "reachCm": 175,
    "stance": "Southpaw",
    "weightClass": "Women's Bantamweight",
    "ranking": 5,
    "record": {
      "wins": 15,
      "losses": 7,
      "draws": 0,
      "ko": 8,
      "sub": 0,
      "dec": 7
    }
  },
  {
    "id": "3136286",
    "slug": "irene-aldana",
    "name": "Irene Aldana",
    "country": "Mexico",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/mex.png",
    "age": 38,
    "heightCm": 175,
    "reachCm": 174,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "ranking": 6,
    "record": {
      "wins": 15,
      "losses": 8,
      "draws": 0,
      "ko": 8,
      "sub": 3,
      "dec": 4
    }
  },
  {
    "id": "3154898",
    "slug": "yana-santos",
    "name": "Yana Santos",
    "country": "Russia",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
    "age": 36,
    "heightCm": 168,
    "reachCm": 173,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "ranking": 7,
    "record": {
      "wins": 17,
      "losses": 8,
      "draws": 0,
      "ko": 7,
      "sub": 1,
      "dec": 9
    }
  },
  {
    "id": "4039865",
    "slug": "ketlen-vieira",
    "name": "Ketlen Vieira",
    "nickname": "Fenomeno",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 34,
    "heightCm": 173,
    "reachCm": 173,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "ranking": 8,
    "record": {
      "wins": 16,
      "losses": 5,
      "draws": 0,
      "ko": 2,
      "sub": 4,
      "dec": 10
    }
  },
  {
    "id": "2995167",
    "slug": "raquel-pennington",
    "name": "Raquel Pennington",
    "nickname": "Rocky",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 37,
    "heightCm": 170,
    "reachCm": 171,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "ranking": 9,
    "record": {
      "wins": 16,
      "losses": 10,
      "draws": 0,
      "ko": 1,
      "sub": 4,
      "dec": 11
    }
  },
  {
    "id": "4334306",
    "slug": "macy-chiasson",
    "name": "Macy Chiasson",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 34,
    "heightCm": 180,
    "reachCm": 183,
    "stance": "Orthodox",
    "weightClass": "Women's Bantamweight",
    "ranking": 10,
    "record": {
      "wins": 11,
      "losses": 6,
      "draws": 0,
      "ko": 4,
      "sub": 3,
      "dec": 4
    }
  },
  {
    "id": "4350762",
    "slug": "zhang-weili",
    "name": "Zhang Weili",
    "nickname": "Magnum",
    "country": "China",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
    "age": 36,
    "heightCm": 163,
    "reachCm": 160,
    "stance": "Switch",
    "weightClass": "Women's Flyweight",
    "ranking": 2,
    "record": {
      "wins": 26,
      "losses": 4,
      "draws": 0,
      "ko": 11,
      "sub": 8,
      "dec": 7
    }
  },
  {
    "id": "2559934",
    "slug": "carla-esparza",
    "name": "Carla Esparza",
    "nickname": "Cookie Monster",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 38,
    "heightCm": 155,
    "reachCm": 160,
    "stance": "Orthodox",
    "weightClass": "Women's Strawweight",
    "ranking": 4,
    "record": {
      "wins": 20,
      "losses": 8,
      "draws": 0,
      "ko": 4,
      "sub": 4,
      "dec": 12
    }
  },
  {
    "id": "4275487",
    "slug": "yan-xiaonan",
    "name": "Yan Xiaonan",
    "country": "China",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
    "age": 36,
    "heightCm": 165,
    "reachCm": 160,
    "stance": "Orthodox",
    "weightClass": "Women's Strawweight",
    "ranking": 5,
    "record": {
      "wins": 19,
      "losses": 5,
      "draws": 0,
      "ko": 8,
      "sub": 1,
      "dec": 10
    }
  },
  {
    "id": "4379258",
    "slug": "marina-rodriguez",
    "name": "Marina Rodriguez",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 39,
    "heightCm": 168,
    "reachCm": 165,
    "stance": "Orthodox",
    "weightClass": "Women's Strawweight",
    "ranking": 6,
    "record": {
      "wins": 17,
      "losses": 6,
      "draws": 2,
      "ko": 7,
      "sub": 1,
      "dec": 9
    }
  },
  {
    "id": "4021217",
    "slug": "mackenzie-dern",
    "name": "Mackenzie Dern",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 33,
    "heightCm": 163,
    "reachCm": 160,
    "stance": "Orthodox",
    "weightClass": "Women's Strawweight",
    "ranking": 7,
    "record": {
      "wins": 16,
      "losses": 5,
      "draws": 0,
      "ko": 0,
      "sub": 8,
      "dec": 8
    }
  },
  {
    "id": "3011878",
    "slug": "claudia-gadelha",
    "name": "Claudia Gadelha",
    "nickname": "Claudinha",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 37,
    "heightCm": 163,
    "reachCm": 160,
    "stance": "Orthodox",
    "weightClass": "Women's Strawweight",
    "ranking": 8,
    "record": {
      "wins": 18,
      "losses": 5,
      "draws": 0,
      "ko": 2,
      "sub": 7,
      "dec": 9
    }
  },
  {
    "id": "2951504",
    "slug": "michelle-waterson-gomez",
    "name": "Michelle Waterson-Gomez",
    "nickname": "The Karate Hottie",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 40,
    "heightCm": 160,
    "reachCm": 157,
    "stance": "Orthodox",
    "weightClass": "Women's Strawweight",
    "ranking": 9,
    "record": {
      "wins": 18,
      "losses": 13,
      "draws": 0,
      "ko": 3,
      "sub": 9,
      "dec": 6
    }
  },
  {
    "id": "3032972",
    "slug": "tecia-pennington",
    "name": "Tecia Pennington",
    "nickname": "The Tiny Tornado",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 36,
    "heightCm": 155,
    "reachCm": 154,
    "stance": "Orthodox",
    "weightClass": "Women's Strawweight",
    "ranking": 10,
    "record": {
      "wins": 15,
      "losses": 8,
      "draws": 0,
      "ko": 1,
      "sub": 1,
      "dec": 13
    }
  },
  {
    "id": "2554705",
    "slug": "valentina-shevchenko",
    "name": "Valentina Shevchenko",
    "nickname": "Bullet",
    "country": "Kyrgyzstan",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/kgz.png",
    "age": 38,
    "heightCm": 165,
    "reachCm": 169,
    "stance": "Southpaw",
    "weightClass": "Women's Flyweight",
    "champion": true,
    "title": "UFC Women's Flyweight Champion",
    "ranking": 0,
    "record": {
      "wins": 26,
      "losses": 4,
      "draws": 1,
      "ko": 8,
      "sub": 7,
      "dec": 11
    }
  },
  {
    "id": "3024395",
    "slug": "jessica-andrade",
    "name": "Jessica Andrade",
    "nickname": "Bate Estaca",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 34,
    "heightCm": 155,
    "reachCm": 157,
    "stance": "Orthodox",
    "weightClass": "Women's Strawweight",
    "ranking": 2,
    "record": {
      "wins": 26,
      "losses": 15,
      "draws": 0,
      "ko": 10,
      "sub": 8,
      "dec": 8
    }
  },
  {
    "id": "4026490",
    "slug": "katlyn-cerminara",
    "name": "Katlyn Cerminara",
    "nickname": "Blonde Fighter",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 37,
    "heightCm": 175,
    "reachCm": 173,
    "stance": "Orthodox",
    "weightClass": "Women's Flyweight",
    "ranking": 3,
    "record": {
      "wins": 18,
      "losses": 6,
      "draws": 0,
      "ko": 2,
      "sub": 1,
      "dec": 15
    }
  },
  {
    "id": "3022348",
    "slug": "jennifer-maia",
    "name": "Jennifer Maia",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 37,
    "heightCm": 163,
    "reachCm": 163,
    "stance": "Orthodox",
    "weightClass": "Women's Flyweight",
    "ranking": 4,
    "record": {
      "wins": 23,
      "losses": 10,
      "draws": 1,
      "ko": 4,
      "sub": 5,
      "dec": 14
    }
  },
  {
    "id": "3028064",
    "slug": "joanne-wood",
    "name": "Joanne Wood",
    "nickname": "JoJo",
    "country": "Scotland",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/sct.png",
    "age": 40,
    "heightCm": 168,
    "reachCm": 166,
    "stance": "Orthodox",
    "weightClass": "Women's Flyweight",
    "ranking": 5,
    "record": {
      "wins": 17,
      "losses": 8,
      "draws": 0,
      "ko": 5,
      "sub": 1,
      "dec": 11
    }
  },
  {
    "id": "3075001",
    "slug": "lauren-murphy",
    "name": "Lauren Murphy",
    "nickname": "Lucky",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 42,
    "heightCm": 165,
    "reachCm": 170,
    "stance": "Orthodox",
    "weightClass": "Women's Flyweight",
    "ranking": 6,
    "record": {
      "wins": 16,
      "losses": 7,
      "draws": 0,
      "ko": 8,
      "sub": 1,
      "dec": 7
    }
  },
  {
    "id": "4257422",
    "slug": "juliana-velasquez",
    "name": "Juliana Velasquez",
    "country": "Brazil",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
    "age": 39,
    "heightCm": 168,
    "reachCm": 173,
    "stance": "--",
    "weightClass": "Women's Flyweight",
    "ranking": 7,
    "record": {
      "wins": 14,
      "losses": 4,
      "draws": 0,
      "ko": 5,
      "sub": 1,
      "dec": 8
    }
  },
  {
    "id": "3924103",
    "slug": "ilima-lei-macfarlane",
    "name": "Ilima-Lei Macfarlane",
    "nickname": "The Iliminator",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 36,
    "heightCm": 163,
    "reachCm": 169,
    "stance": "--",
    "weightClass": "Women's Flyweight",
    "ranking": 8,
    "record": {
      "wins": 13,
      "losses": 3,
      "draws": 0,
      "ko": 2,
      "sub": 6,
      "dec": 5
    }
  },
  {
    "id": "4085155",
    "slug": "cynthia-calvillo",
    "name": "Cynthia Calvillo",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 38,
    "heightCm": 163,
    "reachCm": 163,
    "stance": "Orthodox",
    "weightClass": "Women's Flyweight",
    "ranking": 9,
    "record": {
      "wins": 9,
      "losses": 6,
      "draws": 1,
      "ko": 2,
      "sub": 3,
      "dec": 4
    }
  },
  {
    "id": "2554674",
    "slug": "liz-carmouche",
    "name": "Liz Carmouche",
    "nickname": "Girl-Rilla",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 42,
    "heightCm": 168,
    "reachCm": 168,
    "stance": "Orthodox",
    "weightClass": "Women's Flyweight",
    "ranking": 10,
    "record": {
      "wins": 25,
      "losses": 8,
      "draws": 0,
      "ko": 11,
      "sub": 6,
      "dec": 8
    }
  },
  {
    "id": "4010976",
    "slug": "tom-aspinall",
    "name": "Tom Aspinall",
    "country": "England",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
    "age": 33,
    "heightCm": 196,
    "reachCm": 198,
    "stance": "Orthodox",
    "weightClass": "Heavyweight",
    "record": {
      "wins": 15,
      "losses": 3,
      "draws": 0,
      "ko": 11,
      "sub": 4,
      "dec": 0
    }
  },
  {
    "id": "4695736",
    "slug": "carlos-ulberg",
    "name": "Carlos Ulberg",
    "nickname": "Black Jag",
    "country": "New Zealand",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/nzl.png",
    "age": 35,
    "heightCm": 193,
    "reachCm": 196,
    "stance": "Orthodox",
    "weightClass": "Light Heavyweight",
    "record": {
      "wins": 15,
      "losses": 1,
      "draws": 0,
      "ko": 10,
      "sub": 1,
      "dec": 4
    }
  },
  {
    "id": "3093653",
    "slug": "sean-strickland",
    "name": "Sean Strickland",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 35,
    "heightCm": 185,
    "reachCm": 193,
    "stance": "Orthodox",
    "weightClass": "Middleweight",
    "record": {
      "wins": 31,
      "losses": 7,
      "draws": 0,
      "ko": 12,
      "sub": 4,
      "dec": 15
    }
  },
  {
    "id": "5120301",
    "slug": "joshua-van",
    "name": "Joshua Van",
    "nickname": "The Fearless",
    "country": "Myanmar",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/mya.png",
    "age": 24,
    "heightCm": 165,
    "reachCm": 165,
    "stance": "Orthodox",
    "weightClass": "Flyweight",
    "record": {
      "wins": 17,
      "losses": 2,
      "draws": 0,
      "ko": 9,
      "sub": 2,
      "dec": 6
    }
  },
  {
    "id": "4332765",
    "slug": "kayla-harrison",
    "name": "Kayla Harrison",
    "country": "USA",
    "flag": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
    "age": 35,
    "heightCm": 173,
    "reachCm": 168,
    "stance": "Southpaw",
    "weightClass": "Women's Bantamweight",
    "record": {
      "wins": 19,
      "losses": 1,
      "draws": 0,
      "ko": 6,
      "sub": 8,
      "dec": 5
    }
  }
];

export const REAL_EVENTS: RawEvent[] = [
  {
    "id": "600058854",
    "slug": "ufc-freedom-250-topuria-vs-gaethje",
    "name": "UFC Freedom 250: Topuria vs. Gaethje",
    "org": "UFC",
    "date": "2026-06-15T00:00Z",
    "venue": "South Lawn of the White House",
    "city": "Washington",
    "country": "USA",
    "broadcast": "Paramount+",
    "status": "upcoming",
    "bouts": [
      {
        "id": "b1",
        "fighterA": "3022345",
        "fighterB": "4350812",
        "weightClass": "Lightweight",
        "rounds": 5,
        "boutOrder": 1
      },
      {
        "id": "b2",
        "fighterA": "4426000",
        "fighterB": "4705658",
        "weightClass": "Heavyweight",
        "rounds": 5,
        "boutOrder": 2
      },
      {
        "id": "b3",
        "fighterA": "4079149",
        "fighterB": "4205093",
        "weightClass": "Bantamweight",
        "rounds": 3,
        "boutOrder": 3
      },
      {
        "id": "b4",
        "fighterA": "2560713",
        "fighterB": "4049391",
        "weightClass": "Heavyweight",
        "rounds": 3,
        "boutOrder": 4
      },
      {
        "id": "b5",
        "fighterA": "2504988",
        "fighterB": "5122238",
        "weightClass": "Lightweight",
        "rounds": 3,
        "boutOrder": 5
      },
      {
        "id": "b6",
        "fighterA": "4329444",
        "fighterB": "5061870",
        "weightClass": "Middleweight",
        "rounds": 3,
        "boutOrder": 6
      },
      {
        "id": "b7",
        "fighterA": "3023804",
        "fighterB": "4881999",
        "weightClass": "Featherweight",
        "rounds": 3,
        "boutOrder": 7
      }
    ]
  },
  {
    "id": "600059467",
    "slug": "ufc-fight-night-kape-vs-horiguchi",
    "name": "UFC Fight Night: Kape vs. Horiguchi",
    "org": "UFC",
    "date": "2026-06-20T21:00Z",
    "venue": "Meta APEX",
    "city": "Las Vegas",
    "country": "USA",
    "broadcast": "UFC / ESPN",
    "status": "upcoming",
    "bouts": [
      {
        "id": "e2-b1",
        "fighterA": "4236504",
        "fighterB": "2613374",
        "weightClass": "Flyweight",
        "rounds": 5,
        "boutOrder": 1
      },
      {
        "id": "e2-b2",
        "fighterA": "3994033",
        "fighterB": "5216713",
        "weightClass": "Light Heavyweight",
        "rounds": 3,
        "boutOrder": 2
      },
      {
        "id": "e2-b3",
        "fighterA": "3957071",
        "fighterB": "4884877",
        "weightClass": "Featherweight",
        "rounds": 3,
        "boutOrder": 3
      },
      {
        "id": "e2-b4",
        "fighterA": "5027356",
        "fighterB": "4875511",
        "weightClass": "Featherweight",
        "rounds": 3,
        "boutOrder": 4
      },
      {
        "id": "e2-b5",
        "fighterA": "5157669",
        "fighterB": "5144066",
        "weightClass": "Flyweight",
        "rounds": 3,
        "boutOrder": 5
      },
      {
        "id": "e2-b6",
        "fighterA": "4686734",
        "fighterB": "5308768",
        "weightClass": "Featherweight",
        "rounds": 3,
        "boutOrder": 6
      },
      {
        "id": "e2-b7",
        "fighterA": "5310274",
        "fighterB": "5127984",
        "weightClass": "W Bantamweight",
        "rounds": 3,
        "boutOrder": 7
      },
      {
        "id": "e2-b8",
        "fighterA": "3020408",
        "fighterB": "4815978",
        "weightClass": "Flyweight",
        "rounds": 3,
        "boutOrder": 8
      },
      {
        "id": "e2-b9",
        "fighterA": "4393818",
        "fighterB": "5212738",
        "weightClass": "Featherweight",
        "rounds": 3,
        "boutOrder": 9
      },
      {
        "id": "e2-b10",
        "fighterA": "4292349",
        "fighterB": "5110469",
        "weightClass": "W Bantamweight",
        "rounds": 3,
        "boutOrder": 10
      }
    ]
  },
  {
    "id": "600059254",
    "slug": "ufc-fight-night-fiziev-vs-torres",
    "name": "UFC Fight Night: Fiziev vs. Torres",
    "org": "UFC",
    "date": "2026-06-27T13:00Z",
    "venue": "National Gymnastics Arena",
    "city": "Baku",
    "country": "Azerbaijan",
    "broadcast": "UFC / ESPN",
    "status": "upcoming",
    "bouts": [
      {
        "id": "e3-b1",
        "fighterA": "4339488",
        "fighterB": "4896616",
        "weightClass": "Lightweight",
        "rounds": 5,
        "boutOrder": 1
      },
      {
        "id": "e3-b2",
        "fighterA": "4421784",
        "fighterB": "4418962",
        "weightClass": "Middleweight",
        "rounds": 3,
        "boutOrder": 2
      },
      {
        "id": "e3-b3",
        "fighterA": "5074130",
        "fighterB": "5170144",
        "weightClass": "Lightweight",
        "rounds": 3,
        "boutOrder": 3
      },
      {
        "id": "e3-b4",
        "fighterA": "4294926",
        "fighterB": "4375156",
        "weightClass": "Flyweight",
        "rounds": 3,
        "boutOrder": 4
      },
      {
        "id": "e3-b5",
        "fighterA": "4684776",
        "fighterB": "5077131",
        "weightClass": "Middleweight",
        "rounds": 3,
        "boutOrder": 5
      },
      {
        "id": "e3-b6",
        "fighterA": "3077822",
        "fighterB": "4012999",
        "weightClass": "Middleweight",
        "rounds": 3,
        "boutOrder": 6
      },
      {
        "id": "e3-b7",
        "fighterA": "5350562",
        "fighterB": "5290958",
        "weightClass": "Welterweight",
        "rounds": 3,
        "boutOrder": 7
      },
      {
        "id": "e3-b8",
        "fighterA": "5291025",
        "fighterB": "5264398",
        "weightClass": "Light Heavyweight",
        "rounds": 3,
        "boutOrder": 8
      },
      {
        "id": "e3-b9",
        "fighterA": "4422103",
        "fighterB": "5211225",
        "weightClass": "Middleweight",
        "rounds": 3,
        "boutOrder": 9
      },
      {
        "id": "e3-b10",
        "fighterA": "5204223",
        "fighterB": "4687104",
        "weightClass": "Featherweight",
        "rounds": 3,
        "boutOrder": 10
      },
      {
        "id": "e3-b11",
        "fighterA": "5289841",
        "fighterB": "4738749",
        "weightClass": "Welterweight",
        "rounds": 3,
        "boutOrder": 11
      },
      {
        "id": "e3-b12",
        "fighterA": "5196459",
        "fighterB": "5149439",
        "weightClass": "Bantamweight",
        "rounds": 3,
        "boutOrder": 12
      }
    ]
  },
  {
    "id": "600059148",
    "slug": "ufc-329-mcgregor-vs-holloway-2",
    "name": "UFC 329: McGregor vs. Holloway 2",
    "org": "UFC",
    "date": "2026-07-11T21:00Z",
    "venue": "T-Mobile Arena",
    "city": "Las Vegas",
    "country": "USA",
    "broadcast": "UFC / ESPN",
    "status": "upcoming",
    "bouts": [
      {
        "id": "e4-b1",
        "fighterA": "3022677",
        "fighterB": "2614933",
        "weightClass": "Welterweight",
        "rounds": 5,
        "boutOrder": 1
      },
      {
        "id": "e4-b2",
        "fighterA": "4895362",
        "fighterB": "4008549",
        "weightClass": "Lightweight",
        "rounds": 3,
        "boutOrder": 2
      },
      {
        "id": "e4-b3",
        "fighterA": "4294504",
        "fighterB": "4410868",
        "weightClass": "Bantamweight",
        "rounds": 3,
        "boutOrder": 3
      },
      {
        "id": "e4-b4",
        "fighterA": "4239928",
        "fighterB": "5147737",
        "weightClass": "Flyweight",
        "rounds": 3,
        "boutOrder": 4
      },
      {
        "id": "e4-b5",
        "fighterA": "5214652",
        "fighterB": "5293987",
        "weightClass": "Heavyweight",
        "rounds": 3,
        "boutOrder": 5
      },
      {
        "id": "e4-b6",
        "fighterA": "3009717",
        "fighterB": "3026263",
        "weightClass": "Light Heavyweight",
        "rounds": 3,
        "boutOrder": 6
      },
      {
        "id": "e4-b7",
        "fighterA": "5146696",
        "fighterB": "4688447",
        "weightClass": "Featherweight",
        "rounds": 3,
        "boutOrder": 7
      },
      {
        "id": "e4-b8",
        "fighterA": "5292022",
        "fighterB": "5144068",
        "weightClass": "Middleweight",
        "rounds": 3,
        "boutOrder": 8
      },
      {
        "id": "e4-b9",
        "fighterA": "3163637",
        "fighterB": "3998248",
        "weightClass": "Bantamweight",
        "rounds": 3,
        "boutOrder": 9
      },
      {
        "id": "e4-b10",
        "fighterA": "4424224",
        "fighterB": "4686725",
        "weightClass": "Flyweight",
        "rounds": 3,
        "boutOrder": 10
      },
      {
        "id": "e4-b11",
        "fighterA": "4243624",
        "fighterB": "4215200",
        "weightClass": "W Flyweight",
        "rounds": 3,
        "boutOrder": 11
      },
      {
        "id": "e4-b12",
        "fighterA": "5291085",
        "fighterB": "5143223",
        "weightClass": "Middleweight",
        "rounds": 3,
        "boutOrder": 12
      }
    ]
  }
];

export const REAL_EVENT: RawEvent = REAL_EVENTS[0];
